### ISSUE TITLE
处理 tcp 分包

### ISSUE THREAD

**Issue by zzswang** [36node/32960#10]
## 背景

有时候有一些 tcp 包，会分成几个小包发过来，此时需要通过拼接成整包在处理。

分包和粘包的情况可能会同时存在。

目前已经处理了粘包，需要在粘包处理的基础上，继续考虑分包的情况。

## 需求

- 处理分包
- 增加分包的 testcase

**Comment by zzswang** [comment]
协议

http://www.51bzgf.com/content_bzgf.asp?content_bzgf_id=34415&listpart=54&listtitle=54

**Comment by 0neSe7en** [comment]
暂时定义两个概念：TCP包 和 数据包。
一个TCP包里可能有若干个数据包，也可能有不完整的数据包。
所以，需要把N个TCP包，拆成很多个完整的数据包。并把数据包发给上层做后续处理。

**Comment by zzswang** [comment]
大约想了个流程，参考一下

![image](https://user-images.githubusercontent.com/1524745/48766130-ba7e2180-ecee-11e8-9a26-c12a76d2afe4.png)

**Comment by 0neSe7en** [comment]
嗯嗯，没问题~

**Comment by zzswang** [comment]
当前包的起始是正确的，那么就要清除Rest 

或者

如果当前包，起始正确，但是末尾不完整

那么用当前包作为 rest
