### ISSUE TITLE
[bug] 协议文档描述详细解释

### ISSUE THREAD

**Issue by binsys** [36node/32960#16]
主要涉及的是文档里描述类型为 bit`N`的，没有给对应的json的格式说明及样例（比如json为 number？string？boolean？）

1. 新版-adas-数据解析结果说明
样例里给的
`
accMistake: false,
`
文档描述了 
accMistake | 误踩油门 | bit2 | 00-正常 01-报警
bit2 00 01 与 boolean true false的映射关系
cmcsLevel json会给 0,1,10,还是 0,1,2

2. 支持充电弓车型解析结果说明
涉及bit类型字段的需给出说明。
state 会给 string enum？都是什么
allowLeave 是 boolean嘛？
systemState 给int还是string enum
wifi 同上
soc 是 float？
machineError undefined 是什么意思
等等

3. 零部件能耗解析结果说明
defrostTotal 为 unit32，数据说明是 0~1000 万 KWH，这个值只能是整数嘛？
下面字段同上

**Comment by MiffyLiye** [comment]
@binsys 
这三部分的文档已修复
