### ISSUE TITLE
[feature] 32960文档更新零部件能耗和充电弓的信息

### ISSUE THREAD

**Issue by hauy** [36node/32960#7]
### 需求描述

- [ ] 更新 32960 文档至 v1.6 版本
- [ ] 同步更新原先的 shanghaibus-tbox 工程，将v1.6新增部分协议增加到 其中，文档格式还是保持shanghaibus-tbox工程的格式。这部分文档需要发给 钜乔，可以考虑只更新 adas2 和 零部件能耗。

参考文档：
[车载终端与平台通讯协议修订（V1.6）20190722.docx](https://github.com/36node/32960/files/3562126/V1.6.20190722.docx)

**Comment by zzswang** [comment]
这次主要新增了

```
 * adas2 0x83: "1.6 新版adas",
 * 充电弓 0x84: "chargingBow",
 * 零部件能耗 0x85: "energy"
```

其中需要注意：

### adas2 和 充电弓 是10秒上传数据，也就是说信息会重复10次

https://github.com/36node/32960/blob/master/docs/32960.md#%E4%B8%BB%E5%8A%A8%E5%AE%89%E5%85%A8%E6%95%B0%E6%8D%AE


### 零部件能耗 0x85

参考 https://github.com/36node/32960/blob/master/docs/32960.md#%E6%9E%81%E5%80%BC%E6%95%B0%E6%8D%AE

**Comment by zzswang** [comment]
每一节需要写的基本信息：

0. 概述
1. 二进制样例
2. 二进制格式说明
3. 数据解析结果样例
4. 数据解析结果说明

数据样例，解析结果，在 `src/parser.test.js` 中有
