### ISSUE TITLE
上报信息格式咨询

### ISSUE THREAD

**Issue by itmajun** [36node/32960#9]
32960协议上面说： 上报数据格式为[时间][A标志][A内容]...[B标志][B内容]。 我想咨询下， 这些信息类型不相同， 长度不相同， 如何解析出0x01. 0x02。。。的内容呢？

**Comment by itmajun** [comment]
是这样， 我想把整车数据（0x01）.驱动电机数据(0x02). 等等， 数据都解析出来。 我看代码中只有单独部门的解析， 所以想咨询下， 如果一段报文中拥有这么多类型的数据， 如果把他们区分开解析

**Comment by zzswang** [comment]
这个库可以解析的，看这一段代码

https://github.com/36node/32960/blob/master/src/parser.js#L364

**Comment by zzswang** [comment]
这里面会按个解析，因为每一部分的协议都是定长或者有 length 的

**Comment by itmajun** [comment]
好的， 十分感谢， 我清楚了
